version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - sqlite_data:/app/data  # Zapisuje plik SQLite na stałe
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000 # Żeby frontend wiedział, gdzie uderzać
    depends_on:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  sqlite_data:
