name: CI/CD Pipeline - Monitor Jakości Powietrza

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v4

      - name: Instalacja lintera
        run: pip install flake8

      - name: Linting
        run: flake8 backend/ --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Uwierzytelnianie w Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/704282853205/locations/global/workloadIdentityPools/github-pool/providers/github-project'
          service_account: 'monitor-jp@monitor-jakosci-powietrza.iam.gserviceaccount.com'

      - name: Konfiguracja Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Budowanie i wypychanie obrazu (Cloud Build)
        run: |
          gcloud builds submit --tag gcr.io/monitor-jakosci-powietrza/monitor-app .

      - name: Deploy na Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'monitor-jakosci-powietrza'
          image: 'gcr.io/monitor-jakosci-powietrza/monitor-app'
          region: 'europe-central2'
          flags: '--allow-unauthenticated --service-account=monitor-jp@monitor-jakosci-powietrza.iam.gserviceaccount.com'
